
all: selectserver selectclient

selectserver: selectserver1.c
	gcc -o selectserver selectserver1.c

selectclient: selectclient1.c
	gcc -o selectclient selectclient1.c

clean:
	rm -f *~ selectserver selectclient

